---
version: "3.1"

services:
  meerkat:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - skel_db
    entrypoint:
      - sh
      - .docker/entrypoint.sh
    volumes:
      - ./:/code
    links:
      - skel_db

  nginx:
    build:
      context: ./.docker/nginx/
      dockerfile: Dockerfile
    volumes:
      - ./.docker/nginx/site.conf:/etc/nginx/conf.d/site.template
      - ./.docker/logs/nginx:/var/log/nginx:cached
    ports:
      - "8021:80"
    env_file:
      - .env
    depends_on:
      - meerkat
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  skel_db:
    image: mongo:6.0.3-nanoserver
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - .data/db:/usr/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet

